# Base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy backend source code
COPY . .

# ✅ Copy the environment file
COPY .env .env

# Expose backend port
EXPOSE 3101

# Start the app
CMD ["npm", "run", "start"]
